export const calendarData = {
  '2026-05-01': { status: 'good', region: 'Face', summary: 'Clear complexion, good hydration. No concerns detected.' },
  '2026-05-02': { status: 'good', region: 'Full Body', summary: 'Posture within normal range. Minor shoulder asymmetry noted.' },
  '2026-05-05': { status: 'watch', region: 'Face', summary: 'Mild redness around nose. Slight puffiness under left eye.' },
  '2026-05-06': { status: 'good', region: 'Upper Body', summary: 'Slight forward head posture. Otherwise good alignment.' },
  '2026-05-07': { status: 'good', region: 'Face', summary: 'Skin looks refreshed. Good complexion and hydration.' },
  '2026-05-09': { status: 'watch', region: 'Skin Patch', summary: 'Redness on left forearm. Consistent with previous scans.' },
  '2026-05-10': { status: 'watch', region: 'Face', summary: 'Periorbital darkening noted. Signs of fatigue detected.' },
  '2026-05-12': { status: 'good', region: 'Face', summary: 'Improvement in skin tone. Reduced puffiness.' },
  '2026-05-13': { status: 'good', region: 'Upper Body', summary: 'Posture slightly improved. Shoulder tension visible.' },
  '2026-05-14': { status: 'watch', region: 'Hand', summary: 'Dry knuckles and slight redness on index finger.' },
  '2026-05-15': { status: 'good', region: 'Face', summary: 'Good overall skin health. Hydration levels adequate.' },
  '2026-05-16': { status: 'good', region: 'Full Body', summary: 'Good posture and alignment. No visible concerns.' },
  '2026-05-18': { status: 'alert', region: 'Skin Patch', summary: 'Increased redness and slight texture change on left forearm. Recommend monitoring.' },
  '2026-05-19': { status: 'watch', region: 'Face', summary: 'Fatigue indicators present. Dark circles prominent.' },
  '2026-05-20': { status: 'alert', region: 'Face', summary: 'Significant periorbital darkening. Possible sleep deficit.' },
  '2026-05-21': { status: 'watch', region: 'Upper Body', summary: 'Forward head posture more pronounced. Shoulder rounding observed.' },
  '2026-05-22': { status: 'watch', region: 'Face', summary: 'Skin slightly dull. Possible dehydration.' },
  '2026-05-23': { status: 'good', region: 'Face', summary: 'Improved skin tone after rest. Reduced dark circles.' },
  '2026-05-25': { status: 'good', region: 'Full Body', summary: 'Good posture maintained. Slight weight shift to right noted.' },
  '2026-05-26': { status: 'good', region: 'Face', summary: 'Clear skin. Good hydration and color.' },
  '2026-05-27': { status: 'good', region: 'Upper Body', summary: 'Posture improvement noted. Shoulder alignment better.' },
  '2026-05-28': { status: 'watch', region: 'Skin Patch', summary: 'Forearm patch showing mild improvement but still watch status.' },
  '2026-05-29': { status: 'watch', region: 'Face', summary: 'Some fatigue indicators present. Minor redness.' },
  '2026-05-30': { status: 'good', region: 'Face', summary: 'Good skin health overall. Slight dryness on cheeks.' },
  '2026-05-31': { status: 'watch', region: 'Face', summary: 'Mild periorbital darkening detected. Skin hydration adequate.' },
  '2026-06-01': { status: 'watch', region: 'Face', summary: 'Mild periorbital darkening. Overall health: Watch.' },
}
